[package]
name = "ugsr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
clap = { version = "4.2.7", features = ["derive"] }
config = "0.13.3"
encoding = "0.2.33"
